# Khai báo thông tin project (lấy từ link SonarCloud của bạn)
sonar.projectKey=nguyentuancuong112005_web_Pharmar_official
sonar.organization=nguyentuancuong112005
sonar.projectName=web_Pharmar_official

# Chỉ định các thư mục chứa code cần quét (bỏ qua node_modules và các file sql)
sonar.sources=back_end_managements,font_end_managements
sonar.exclusions=**/node_modules/**, Mysql/**, **/*.sql

# Chỉ định nơi chứa file test và các file cần chạy test
sonar.tests=back_end_managements
sonar.test.inclusions=back_end_managements/**/*.test.js, back_end_managements/**/*.spec.js

# ĐÂY LÀ DÒNG CHỈ ĐƯỜNG DẪN ĐẾN FILE COVERAGE
sonar.javascript.lcov.reportPaths=back_end_managements/coverage/lcov.info