name: CI Pipeline

on:
  push:
    branches: [ "main", "master" ] # Tự động chạy khi push lên main hoặc master

jobs:
  check-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: npm install
        working-directory: back_end_managements

      - name: Run tests & coverage
        run: npx jest --coverage
        working-directory: back_end_managements

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          # Cấu hình quét được nhét thẳng vào đây, không cần file phụ nữa!
          args: >
            -Dsonar.projectKey=nguyentuancuong112005_web_Pharmar_official
            -Dsonar.organization=nguyentuancuong112005
            -Dsonar.sources=back_end_managements,font_end_managements
            -Dsonar.exclusions=**/node_modules/**,Mysql/**,**/*.sql
            -Dsonar.tests=back_end_managements
            -Dsonar.test.inclusions=back_end_managements/**/*.test.js
            -Dsonar.javascript.lcov.reportPaths=back_end_managements/coverage/lcov.info